CREATE TABLE codec_compat.dml_temporal_table (
  id INT PRIMARY KEY,
  c_date DATE,
  c_datetime_0 DATETIME(0),
  c_datetime_1 DATETIME(1),
  c_datetime_2 DATETIME(2),
  c_datetime_3 DATETIME(3),
  c_datetime_4 DATETIME(4),
  c_datetime_5 DATETIME(5),
  c_datetime_6 DATETIME(6),
  c_timestamp_0 TIMESTAMP(0) NULL,
  c_timestamp_1 TIMESTAMP(1) NULL,
  c_timestamp_2 TIMESTAMP(2) NULL,
  c_timestamp_3 TIMESTAMP(3) NULL,
  c_timestamp_4 TIMESTAMP(4) NULL,
  c_timestamp_5 TIMESTAMP(5) NULL,
  c_timestamp_6 TIMESTAMP(6) NULL,
  c_time_0 TIME(0),
  c_time_1 TIME(1),
  c_time_2 TIME(2),
  c_time_3 TIME(3),
  c_time_4 TIME(4),
  c_time_5 TIME(5),
  c_time_6 TIME(6),
  c_year YEAR,
  c_year_4 YEAR(4)
);
